### ISSUE TITLE
Firefox warning: Event pages are not supported

### ISSUE THREAD

**Issue by samwilson** [99of9/Entity-Explosion#1]
When loading in Firefox, the following warning is shown:

> Reading manifest: Warning processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

It doesn't seem to affect operation.

**Comment by 99of9** [comment]
Thanks for testing in Firefox. If it's already operating without too many problems, that bodes well for a conversion!

**Comment by samwilson** [comment]
Yep! Looks pretty good. I'll see if I can figure out what's going on with this warning, because I guess it'd have to be resolved before adding it to the Addons store. Will send a PR if I sort anything out.

**Comment by 99of9** [comment]
It sounds like it's referring to this in the manifest:
  "background": {
     "scripts": ["jquery.min.js", "background.js"],
	 "persistent": false
  },

Maybe just remove the "persistent" tag, because it's not needed (which may be the default).
