### ISSUE TITLE
Set up Property P8168

### ISSUE THREAD

**Issue by salgo60** [99of9/Entity-Explosion#11]
Hi Toby

I need help how to set up [Property:P8168](https://www.wikidata.org/wiki/Property:P8168) that is a Wikibase database for historical research we try to match with WIkidata see [Task T266745](https://phabricator.wikimedia.org/T266745)

* Factgrid [Item:Q176477](https://database.factgrid.de/wiki/Item:Q176477) is same as [Wikidata Q15695036](https://www.wikidata.org/wiki/Q15695036) but it fails?!?!?
* the other way around is no problem see [video](https://www.youtube.com/watch?v=IFEjTJLvGB4)

![image](https://user-images.githubusercontent.com/14206509/98368232-4d790900-2037-11eb-827e-bef14895dc83.png)

**Comment by 99of9** [comment]
Thanks for the report. Sorry I only saw it just now. I'll look into this - I can't see anything you've done wrong.

**Comment by 99of9** [comment]
Oh, I got it. It needed a "format as a regular expression" on the Factgrid property. Now fixed and working.  https://www.wikidata.org/w/index.php?title=Property%3AP8168&type=revision&diff=1392095730&oldid=1371507723
