### ISSUE TITLE
Please add support of Yandex Music

### ISSUE THREAD

**Issue by vitaly-zdanevich** [99of9/Entity-Explosion#25]
https://music.yandex.ru/artist/4526472

links to 

https://www.wikidata.org/wiki/Q100269171

**Comment by 99of9** [comment]
This one works for me. Can you provide more information, or test on other artists on Yanex Music?

![image](https://github.com/99of9/Entity-Explosion/assets/13860532/e3eaf903-c9bc-42dd-ba71-bfdb3ccb69c0)

**Comment by vitaly-zdanevich** [comment]
Hmmmm ops yep now it works for me.
