### ISSUE TITLE
Frozen for GitHub repos

### ISSUE THREAD

**Issue by vitaly-zdanevich** [99of9/Entity-Explosion#26]
For example https://github.com/organicmaps/organicmaps

**Comment by 99of9** [comment]
It looks like this one works, but matches two items. I think I need to make it clearer to the user when we need to select from multiple options.
![image](https://github.com/99of9/Entity-Explosion/assets/13860532/3fcaf145-0cb6-47c9-81fc-82eb454a398b)

**Comment by vitaly-zdanevich** [comment]
Oh, it works when I select something, but nothing by default.

**Comment by 99of9** [comment]
Thanks. I'll close this task and replace it with #34
