### ISSUE TITLE
Nothing for https://ru.wikipedia.org/wiki/BelarusDocs

### ISSUE THREAD

**Issue by vitaly-zdanevich** [99of9/Entity-Explosion#32]

**Comment by 99of9** [comment]
This one works for me. Can I get more information on what you see? Does it work for other pages on other Wikipedias?
![image](https://github.com/99of9/Entity-Explosion/assets/13860532/21e88f66-fb81-4209-887f-f0816257fe95)

**Comment by vitaly-zdanevich** [comment]
Wow, now it works for me...
