### ISSUE TITLE
Please make link from Reddit

### ISSUE THREAD

**Issue by vitaly-zdanevich** [99of9/Entity-Explosion#33]
https://www.reddit.com/r/Gentoo/
to
https://www.wikidata.org/wiki/Q170378

**Comment by 99of9** [comment]
I've added the required property to the Wikidata item: https://www.wikidata.org/w/index.php?title=Q170378&diff=2143258593&oldid=2125972001

It works for other subreddits, e.g. https://www.reddit.com/r/science/ so I'm hopeful it will work, but the ?rdt= parameter may confuse it. I'll check back later on this.

**Comment by 99of9** [comment]
https://www.reddit.com/r/Gentoo/ works for me now
https://www.reddit.com/r/Gentoo/?rdt=35529 still doesn't, but that is a more challenging case that will hopefully be caught when #19 is addressed
