### ISSUE TITLE
get version info in the Chrome extension

### ISSUE THREAD

**Issue by salgo60** [99of9/Entity-Explosion#5]
As this is an extension in development I guess we should have a version number easy available 

![image](https://user-images.githubusercontent.com/14206509/91797105-0d09a300-ec22-11ea-9693-c56efb1766cc.png)

**Comment by 99of9** [comment]
Good idea. 
https://stackoverflow.com/questions/7573191/can-i-access-a-property-from-my-manifest-json-in-my-extensions-javascript-files

**Comment by 99of9** [comment]
This has been added to version 0.8.5. Thanks for the suggestion.
