### ISSUE TITLE
Icons should be square

### ISSUE THREAD

**Issue by samwilson** [99of9/Entity-Explosion#7]
According to `web-ext lint`, the icons should be square:

```
ERRORS:

Code                                 Message           Description                        File            Line   Column
ICON_NOT_SQUARE                      Icons must be     Icon at "EE-grey-38.png" must be   manifest.json                
                                     square.           square.                                                         
```

Both browsers say the same (although they helpfully don't actually say 'square', but all the examples are square):

* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons
* https://developer.chrome.com/extensions/manifest/icons

**Comment by 99of9** [comment]
Do you have the latest version? I stretched them all to 38x38 about a week ago.

**Comment by samwilson** [comment]
Oh yes! Oops. I feel a bit silly. :-)
