### ISSUE TITLE
Wikidata properties with support for more languages

### ISSUE THREAD

**Issue by salgo60** [99of9/Entity-Explosion#8]
![image](https://user-images.githubusercontent.com/14206509/92204900-d54e6580-ee84-11ea-8bf6-4f46a8641ba7.png)

dont know if it is a good pattern but its used when we have support for more languages in the external sources
* https://www.wikidata.org/wiki/Property:P7704#P1630
* https://www.wikidata.org/wiki/Property:P4963#P1630

**Comment by 99of9** [comment]
At the moment it only picks up the truthy (highest priority) formatter, but I have been working on both broadening that and filtering results so it prefers to show outlinks to the language you queried in.

**Comment by 99of9** [comment]
I've had a stab at using this information for filtering in version 0.8.5. See if it behaves as you would expect.
